<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

if (false) {
    /**
     * This class is deprecated. Use Cloud_Py_API\DbCursorReply\columnData instead.
     * @deprecated
     */
    class DbCursorReply_columnData {}
}
class_exists(DbCursorReply\columnData::class);
@trigger_error('Cloud_Py_API\DbCursorReply_columnData is deprecated and will be removed in the next major release. Use Cloud_Py_API\DbCursorReply\columnData instead', E_USER_DEPRECATED);

