<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

if (false) {
    /**
     * This class is deprecated. Use Cloud_Py_API\DbSelectRequest\joinType instead.
     * @deprecated
     */
    class DbSelectRequest_joinType {}
}
class_exists(DbSelectRequest\joinType::class);
@trigger_error('Cloud_Py_API\DbSelectRequest_joinType is deprecated and will be removed in the next major release. Use Cloud_Py_API\DbSelectRequest\joinType instead', E_USER_DEPRECATED);

