<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

if (false) {
    /**
     * This class is deprecated. Use Cloud_Py_API\DbSelectRequest\havingExpr instead.
     * @deprecated
     */
    class DbSelectRequest_havingExpr {}
}
class_exists(DbSelectRequest\havingExpr::class);
@trigger_error('Cloud_Py_API\DbSelectRequest_havingExpr is deprecated and will be removed in the next major release. Use Cloud_Py_API\DbSelectRequest\havingExpr instead', E_USER_DEPRECATED);

