<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

if (false) {
    /**
     * This class is deprecated. Use Cloud_Py_API\ServerCommand\cmd_id instead.
     * @deprecated
     */
    class ServerCommand_cmd_id {}
}
class_exists(ServerCommand\cmd_id::class);
@trigger_error('Cloud_Py_API\ServerCommand_cmd_id is deprecated and will be removed in the next major release. Use Cloud_Py_API\ServerCommand\cmd_id instead', E_USER_DEPRECATED);

