<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Reply for TaskState. Client send it every ~5 sec.
 *
 * Generated from protobuf message <code>Cloud_Py_API.TaskStateReply</code>
 */
class TaskStateReply extends \Google\Protobuf\Internal\Message
{
    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool stop = 1;</code>
     */
    protected $stop = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $stop
     *          If true client must gracefully stop it's work.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool stop = 1;</code>
     * @return bool
     */
    public function getStop()
    {
        return $this->stop;
    }

    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool stop = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStop($var)
    {
        GPBUtil::checkBool($var);
        $this->stop = $var;

        return $this;
    }

}

