<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API;

if (false) {
    /**
     * This class is deprecated. Use Cloud_Py_API\TaskInitReply\cfgOptions instead.
     * @deprecated
     */
    class TaskInitReply_cfgOptions {}
}
class_exists(TaskInitReply\cfgOptions::class);
@trigger_error('Cloud_Py_API\TaskInitReply_cfgOptions is deprecated and will be removed in the next major release. Use Cloud_Py_API\TaskInitReply\cfgOptions instead', E_USER_DEPRECATED);

