<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

namespace TaskInitReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TaskInitReply.cfgOptions</code>
 */
class cfgOptions extends \Google\Protobuf\Internal\Message
{
    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.logLvl log_lvl = 1;</code>
     */
    protected $log_lvl = 0;
    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     */
    protected $dataFolder = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $log_lvl
     *          0-4 , level logs from NC documentation.
     *     @type string $dataFolder
     *          Path to NC data folder.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.logLvl log_lvl = 1;</code>
     * @return int
     */
    public function getLogLvl()
    {
        return $this->log_lvl;
    }

    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.logLvl log_lvl = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogLvl($var)
    {
        GPBUtil::checkEnum($var, \logLvl::class);
        $this->log_lvl = $var;

        return $this;
    }

    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @return string
     */
    public function getDataFolder()
    {
        return $this->dataFolder;
    }

    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDataFolder($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataFolder = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(cfgOptions::class, \TaskInitReply_cfgOptions::class);

