<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\CheckDataRequest\missing_pckg instead.
     * @deprecated
     */
    class CheckDataRequest_missing_pckg {}
}
class_exists(CheckDataRequest\missing_pckg::class);
@trigger_error('OCA\Cloud_Py_API\Proto\CheckDataRequest_missing_pckg is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\CheckDataRequest\missing_pckg instead', E_USER_DEPRECATED);

