<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.dbConfig</code>
 */
class dbConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 1;</code>
     */
    protected $dbType = '';
    /**
     * DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 2;</code>
     */
    protected $dbUser = '';
    /**
     * DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 3;</code>
     */
    protected $dbPass = '';
    /**
     * DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 4;</code>
     */
    protected $dbHost = '';
    /**
     * DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 5;</code>
     */
    protected $dbName = '';
    /**
     * DB tables prefix configuration
     *
     * Generated from protobuf field <code>string dbPrefix = 6;</code>
     */
    protected $dbPrefix = '';
    /**
     * DB Socket configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbSocket = 7;</code>
     */
    protected $iniDbSocket = '';
    /**
     * DB Host configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbHost = 8;</code>
     */
    protected $iniDbHost = '';
    /**
     * DB Port configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbPort = 9;</code>
     */
    protected $iniDbPort = '';
    /**
     * DB MYSQL_ATTR_SSL_KEY configuration
     *
     * Generated from protobuf field <code>string dbDriverSslKey = 10;</code>
     */
    protected $dbDriverSslKey = '';
    /**
     * DB MYSQL_ATTR_SSL_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCert = 11;</code>
     */
    protected $dbDriverSslCert = '';
    /**
     * DB MYSQL_ATTR_SSL_CA configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCa = 12;</code>
     */
    protected $dbDriverSslCa = '';
    /**
     * DB MYSQL_ATTR_SSL_VERIFY_SERVER_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslVerifyCrt = 13;</code>
     */
    protected $dbDriverSslVerifyCrt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbType
     *           DB Type configuration
     *     @type string $dbUser
     *           DB User configuration
     *     @type string $dbPass
     *           DB Password configuration
     *     @type string $dbHost
     *           DB Host configuration
     *     @type string $dbName
     *           DB Name configuration
     *     @type string $dbPrefix
     *           DB tables prefix configuration
     *     @type string $iniDbSocket
     *           DB Socket configuration from ini (mysql)
     *     @type string $iniDbHost
     *           DB Host configuration from ini (mysql)
     *     @type string $iniDbPort
     *           DB Port configuration from ini (mysql)
     *     @type string $dbDriverSslKey
     *           DB MYSQL_ATTR_SSL_KEY configuration
     *     @type string $dbDriverSslCert
     *           DB MYSQL_ATTR_SSL_CERT configuration
     *     @type string $dbDriverSslCa
     *           DB MYSQL_ATTR_SSL_CA configuration
     *     @type string $dbDriverSslVerifyCrt
     *           DB MYSQL_ATTR_SSL_VERIFY_SERVER_CERT configuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 1;</code>
     * @return string
     */
    public function getDbType()
    {
        return $this->dbType;
    }

    /**
     * DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbType($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbType = $var;

        return $this;
    }

    /**
     * DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 2;</code>
     * @return string
     */
    public function getDbUser()
    {
        return $this->dbUser;
    }

    /**
     * DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbUser = $var;

        return $this;
    }

    /**
     * DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 3;</code>
     * @return string
     */
    public function getDbPass()
    {
        return $this->dbPass;
    }

    /**
     * DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbPass($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbPass = $var;

        return $this;
    }

    /**
     * DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 4;</code>
     * @return string
     */
    public function getDbHost()
    {
        return $this->dbHost;
    }

    /**
     * DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDbHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbHost = $var;

        return $this;
    }

    /**
     * DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 5;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbName = $var;

        return $this;
    }

    /**
     * DB tables prefix configuration
     *
     * Generated from protobuf field <code>string dbPrefix = 6;</code>
     * @return string
     */
    public function getDbPrefix()
    {
        return $this->dbPrefix;
    }

    /**
     * DB tables prefix configuration
     *
     * Generated from protobuf field <code>string dbPrefix = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDbPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbPrefix = $var;

        return $this;
    }

    /**
     * DB Socket configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbSocket = 7;</code>
     * @return string
     */
    public function getIniDbSocket()
    {
        return $this->iniDbSocket;
    }

    /**
     * DB Socket configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbSocket = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIniDbSocket($var)
    {
        GPBUtil::checkString($var, True);
        $this->iniDbSocket = $var;

        return $this;
    }

    /**
     * DB Host configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbHost = 8;</code>
     * @return string
     */
    public function getIniDbHost()
    {
        return $this->iniDbHost;
    }

    /**
     * DB Host configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbHost = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIniDbHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->iniDbHost = $var;

        return $this;
    }

    /**
     * DB Port configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbPort = 9;</code>
     * @return string
     */
    public function getIniDbPort()
    {
        return $this->iniDbPort;
    }

    /**
     * DB Port configuration from ini (mysql)
     *
     * Generated from protobuf field <code>string iniDbPort = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setIniDbPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->iniDbPort = $var;

        return $this;
    }

    /**
     * DB MYSQL_ATTR_SSL_KEY configuration
     *
     * Generated from protobuf field <code>string dbDriverSslKey = 10;</code>
     * @return string
     */
    public function getDbDriverSslKey()
    {
        return $this->dbDriverSslKey;
    }

    /**
     * DB MYSQL_ATTR_SSL_KEY configuration
     *
     * Generated from protobuf field <code>string dbDriverSslKey = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDbDriverSslKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbDriverSslKey = $var;

        return $this;
    }

    /**
     * DB MYSQL_ATTR_SSL_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCert = 11;</code>
     * @return string
     */
    public function getDbDriverSslCert()
    {
        return $this->dbDriverSslCert;
    }

    /**
     * DB MYSQL_ATTR_SSL_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCert = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setDbDriverSslCert($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbDriverSslCert = $var;

        return $this;
    }

    /**
     * DB MYSQL_ATTR_SSL_CA configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCa = 12;</code>
     * @return string
     */
    public function getDbDriverSslCa()
    {
        return $this->dbDriverSslCa;
    }

    /**
     * DB MYSQL_ATTR_SSL_CA configuration
     *
     * Generated from protobuf field <code>string dbDriverSslCa = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDbDriverSslCa($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbDriverSslCa = $var;

        return $this;
    }

    /**
     * DB MYSQL_ATTR_SSL_VERIFY_SERVER_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslVerifyCrt = 13;</code>
     * @return string
     */
    public function getDbDriverSslVerifyCrt()
    {
        return $this->dbDriverSslVerifyCrt;
    }

    /**
     * DB MYSQL_ATTR_SSL_VERIFY_SERVER_CERT configuration
     *
     * Generated from protobuf field <code>string dbDriverSslVerifyCrt = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setDbDriverSslVerifyCrt($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbDriverSslVerifyCrt = $var;

        return $this;
    }

}

