<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.dbConfig</code>
 */
class dbConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Current DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 1;</code>
     */
    protected $dbHost = '';
    /**
     * Current DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 2;</code>
     */
    protected $dbType = '';
    /**
     * Current DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 3;</code>
     */
    protected $dbName = '';
    /**
     * Current DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 4;</code>
     */
    protected $dbUser = '';
    /**
     * Current DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 5;</code>
     */
    protected $dbPass = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dbHost
     *           Current DB Host configuration
     *     @type string $dbType
     *           Current DB Type configuration
     *     @type string $dbName
     *           Current DB Name configuration
     *     @type string $dbUser
     *           Current DB User configuration
     *     @type string $dbPass
     *           Current DB Password configuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Current DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 1;</code>
     * @return string
     */
    public function getDbHost()
    {
        return $this->dbHost;
    }

    /**
     * Current DB Host configuration
     *
     * Generated from protobuf field <code>string dbHost = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDbHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbHost = $var;

        return $this;
    }

    /**
     * Current DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 2;</code>
     * @return string
     */
    public function getDbType()
    {
        return $this->dbType;
    }

    /**
     * Current DB Type configuration
     *
     * Generated from protobuf field <code>string dbType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDbType($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbType = $var;

        return $this;
    }

    /**
     * Current DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 3;</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }

    /**
     * Current DB Name configuration
     *
     * Generated from protobuf field <code>string dbName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbName = $var;

        return $this;
    }

    /**
     * Current DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 4;</code>
     * @return string
     */
    public function getDbUser()
    {
        return $this->dbUser;
    }

    /**
     * Current DB User configuration
     *
     * Generated from protobuf field <code>string dbUser = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDbUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbUser = $var;

        return $this;
    }

    /**
     * Current DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 5;</code>
     * @return string
     */
    public function getDbPass()
    {
        return $this->dbPass;
    }

    /**
     * Current DB Password configuration
     *
     * Generated from protobuf field <code>string dbPass = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDbPass($var)
    {
        GPBUtil::checkString($var, True);
        $this->dbPass = $var;

        return $this;
    }

}

