<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\DbCursorRequest\cCmd instead.
     * @deprecated
     */
    class DbCursorRequest_cCmd {}
}
class_exists(DbCursorRequest\cCmd::class);
@trigger_error('OCA\Cloud_Py_API\Proto\DbCursorRequest_cCmd is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\DbCursorRequest\cCmd instead', E_USER_DEPRECATED);

