<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\DbCursorReply\columnData instead.
     * @deprecated
     */
    class DbCursorReply_columnData {}
}
class_exists(DbCursorReply\columnData::class);
@trigger_error('OCA\Cloud_Py_API\Proto\DbCursorReply_columnData is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\DbCursorReply\columnData instead', E_USER_DEPRECATED);

