<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.DbExecRequest</code>
 */
class DbExecRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.DbExecRequest.rType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     */
    protected $table_name = '';
    /**
     * Generated from protobuf field <code>repeated string columns = 3;</code>
     */
    private $columns;
    /**
     * Generated from protobuf field <code>repeated bytes values = 4;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 5;</code>
     */
    private $whereas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $table_name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $columns
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $values
     *     @type \OCA\Cloud_Py_API\Proto\whereExpr[]|\Google\Protobuf\Internal\RepeatedField $whereas
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.DbExecRequest.rType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.DbExecRequest.rType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\DbExecRequest\rType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string columns = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>repeated string columns = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes values = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated bytes values = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhereas()
    {
        return $this->whereas;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 5;</code>
     * @param \OCA\Cloud_Py_API\Proto\whereExpr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhereas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\whereExpr::class);
        $this->whereas = $arr;

        return $this;
    }

}

