<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\DbExecRequest\rType instead.
     * @deprecated
     */
    class DbExecRequest_rType {}
}
class_exists(DbExecRequest\rType::class);
@trigger_error('OCA\Cloud_Py_API\Proto\DbExecRequest_rType is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\DbExecRequest\rType instead', E_USER_DEPRECATED);

