<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\DbSelectRequest\havingExpr instead.
     * @deprecated
     */
    class DbSelectRequest_havingExpr {}
}
class_exists(DbSelectRequest\havingExpr::class);
@trigger_error('OCA\Cloud_Py_API\Proto\DbSelectRequest_havingExpr is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\DbSelectRequest\havingExpr instead', E_USER_DEPRECATED);

