<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.DbSelectRequest</code>
 */
class DbSelectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias columns = 1;</code>
     */
    private $columns;
    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias from = 2;</code>
     */
    private $from;
    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.joinType joins = 3;</code>
     */
    private $joins;
    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 4;</code>
     */
    private $whereas;
    /**
     * Generated from protobuf field <code>repeated string groupBy = 5;</code>
     */
    private $groupBy;
    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.havingExpr havings = 6;</code>
     */
    private $havings;
    /**
     * Generated from protobuf field <code>repeated string orderBy = 7;</code>
     */
    private $orderBy;
    /**
     * Generated from protobuf field <code>int64 maxResults = 8;</code>
     */
    protected $maxResults = 0;
    /**
     * Generated from protobuf field <code>int64 firstResult = 9;</code>
     */
    protected $firstResult = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OCA\Cloud_Py_API\Proto\str_alias[]|\Google\Protobuf\Internal\RepeatedField $columns
     *          aliases or filed names.
     *     @type \OCA\Cloud_Py_API\Proto\str_alias[]|\Google\Protobuf\Internal\RepeatedField $from
     *     @type \OCA\Cloud_Py_API\Proto\DbSelectRequest\joinType[]|\Google\Protobuf\Internal\RepeatedField $joins
     *     @type \OCA\Cloud_Py_API\Proto\whereExpr[]|\Google\Protobuf\Internal\RepeatedField $whereas
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $groupBy
     *     @type \OCA\Cloud_Py_API\Proto\DbSelectRequest\havingExpr[]|\Google\Protobuf\Internal\RepeatedField $havings
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $orderBy
     *     @type int|string $maxResults
     *     @type int|string $firstResult
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias columns = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias columns = 1;</code>
     * @param \OCA\Cloud_Py_API\Proto\str_alias[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\str_alias::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias from = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.str_alias from = 2;</code>
     * @param \OCA\Cloud_Py_API\Proto\str_alias[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrom($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\str_alias::class);
        $this->from = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.joinType joins = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJoins()
    {
        return $this->joins;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.joinType joins = 3;</code>
     * @param \OCA\Cloud_Py_API\Proto\DbSelectRequest\joinType[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJoins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\DbSelectRequest\joinType::class);
        $this->joins = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhereas()
    {
        return $this->whereas;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.whereExpr whereas = 4;</code>
     * @param \OCA\Cloud_Py_API\Proto\whereExpr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhereas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\whereExpr::class);
        $this->whereas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string groupBy = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupBy()
    {
        return $this->groupBy;
    }

    /**
     * Generated from protobuf field <code>repeated string groupBy = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->groupBy = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.havingExpr havings = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHavings()
    {
        return $this->havings;
    }

    /**
     * Generated from protobuf field <code>repeated .OCA.Cloud_Py_API.Proto.DbSelectRequest.havingExpr havings = 6;</code>
     * @param \OCA\Cloud_Py_API\Proto\DbSelectRequest\havingExpr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHavings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OCA\Cloud_Py_API\Proto\DbSelectRequest\havingExpr::class);
        $this->havings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string orderBy = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderBy()
    {
        return $this->orderBy;
    }

    /**
     * Generated from protobuf field <code>repeated string orderBy = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->orderBy = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 maxResults = 8;</code>
     * @return int|string
     */
    public function getMaxResults()
    {
        return $this->maxResults;
    }

    /**
     * Generated from protobuf field <code>int64 maxResults = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxResults($var)
    {
        GPBUtil::checkInt64($var);
        $this->maxResults = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 firstResult = 9;</code>
     * @return int|string
     */
    public function getFirstResult()
    {
        return $this->firstResult;
    }

    /**
     * Generated from protobuf field <code>int64 firstResult = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirstResult($var)
    {
        GPBUtil::checkInt64($var);
        $this->firstResult = $var;

        return $this;
    }

}

