<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\DbSelectRequest\joinType instead.
     * @deprecated
     */
    class DbSelectRequest_joinType {}
}
class_exists(DbSelectRequest\joinType::class);
@trigger_error('OCA\Cloud_Py_API\Proto\DbSelectRequest_joinType is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\DbSelectRequest\joinType instead', E_USER_DEPRECATED);

