<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>OCA.Cloud_Py_API.Proto.exprType</code>
 */
class exprType
{
    /**
     * Generated from protobuf enum <code>EQ = 0;</code>
     */
    const EQ = 0;
    /**
     * Generated from protobuf enum <code>NEQ = 1;</code>
     */
    const NEQ = 1;
    /**
     * Generated from protobuf enum <code>LT = 2;</code>
     */
    const LT = 2;
    /**
     * Generated from protobuf enum <code>LTE = 3;</code>
     */
    const LTE = 3;
    /**
     * Generated from protobuf enum <code>GT = 4;</code>
     */
    const GT = 4;
    /**
     * Generated from protobuf enum <code>GTE = 5;</code>
     */
    const GTE = 5;
    /**
     * Generated from protobuf enum <code>IS_NULL = 6;</code>
     */
    const IS_NULL = 6;
    /**
     * Generated from protobuf enum <code>IS_NOT_NULL = 7;</code>
     */
    const IS_NOT_NULL = 7;
    /**
     * Generated from protobuf enum <code>LIKE = 8;</code>
     */
    const LIKE = 8;
    /**
     * Generated from protobuf enum <code>NOT_LINE = 9;</code>
     */
    const NOT_LINE = 9;
    /**
     * Generated from protobuf enum <code>IN = 10;</code>
     */
    const IN = 10;
    /**
     * Generated from protobuf enum <code>NOT_IN = 11;</code>
     */
    const NOT_IN = 11;

    private static $valueToName = [
        self::EQ => 'EQ',
        self::NEQ => 'NEQ',
        self::LT => 'LT',
        self::LTE => 'LTE',
        self::GT => 'GT',
        self::GTE => 'GTE',
        self::IS_NULL => 'IS_NULL',
        self::IS_NOT_NULL => 'IS_NOT_NULL',
        self::LIKE => 'LIKE',
        self::NOT_LINE => 'NOT_LINE',
        self::IN => 'IN',
        self::NOT_IN => 'NOT_IN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

