<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Reply for this is a FsMoveReply message.
 *
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.FsMoveRequest</code>
 */
class FsMoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     */
    protected $fileId = null;
    /**
     *absolute path relative to MP.
     *
     * Generated from protobuf field <code>string targetPath = 2;</code>
     */
    protected $targetPath = '';
    /**
     * Generated from protobuf field <code>bool copy = 3;</code>
     */
    protected $copy = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OCA\Cloud_Py_API\Proto\fsId $fileId
     *     @type string $targetPath
     *          absolute path relative to MP.
     *     @type bool $copy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     * @return \OCA\Cloud_Py_API\Proto\fsId|null
     */
    public function getFileId()
    {
        return $this->fileId;
    }

    public function hasFileId()
    {
        return isset($this->fileId);
    }

    public function clearFileId()
    {
        unset($this->fileId);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     * @param \OCA\Cloud_Py_API\Proto\fsId $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkMessage($var, \OCA\Cloud_Py_API\Proto\fsId::class);
        $this->fileId = $var;

        return $this;
    }

    /**
     *absolute path relative to MP.
     *
     * Generated from protobuf field <code>string targetPath = 2;</code>
     * @return string
     */
    public function getTargetPath()
    {
        return $this->targetPath;
    }

    /**
     *absolute path relative to MP.
     *
     * Generated from protobuf field <code>string targetPath = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->targetPath = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool copy = 3;</code>
     * @return bool
     */
    public function getCopy()
    {
        return $this->copy;
    }

    /**
     * Generated from protobuf field <code>bool copy = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setCopy($var)
    {
        GPBUtil::checkBool($var);
        $this->copy = $var;

        return $this;
    }

}

