<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fs.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.FsNodeInfo</code>
 */
class FsNodeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     */
    protected $fileId = null;
    /**
     * Generated from protobuf field <code>bool is_dir = 2;</code>
     */
    protected $is_dir = false;
    /**
     * Generated from protobuf field <code>bool is_local = 3;</code>
     */
    protected $is_local = false;
    /**
     * Generated from protobuf field <code>string mimetype = 4;</code>
     */
    protected $mimetype = '';
    /**
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string internal_path = 6;</code>
     */
    protected $internal_path = '';
    /**
     * Generated from protobuf field <code>string abs_path = 7;</code>
     */
    protected $abs_path = '';
    /**
     * Generated from protobuf field <code>int64 size = 8;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>int64 permissions = 9;</code>
     */
    protected $permissions = 0;
    /**
     * Generated from protobuf field <code>int64 mtime = 10;</code>
     */
    protected $mtime = 0;
    /**
     * Generated from protobuf field <code>string checksum = 11;</code>
     */
    protected $checksum = '';
    /**
     * Generated from protobuf field <code>bool encrypted = 12;</code>
     */
    protected $encrypted = false;
    /**
     * Generated from protobuf field <code>string etag = 13;</code>
     */
    protected $etag = '';
    /**
     * Generated from protobuf field <code>string ownerName = 14;</code>
     */
    protected $ownerName = '';
    /**
     * Generated from protobuf field <code>string storageId = 15;</code>
     */
    protected $storageId = '';
    /**
     * Generated from protobuf field <code>int64 mountId = 16;</code>
     */
    protected $mountId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \OCA\Cloud_Py_API\Proto\fsId $fileId
     *     @type bool $is_dir
     *     @type bool $is_local
     *     @type string $mimetype
     *     @type string $name
     *     @type string $internal_path
     *     @type string $abs_path
     *     @type int|string $size
     *     @type int|string $permissions
     *     @type int|string $mtime
     *     @type string $checksum
     *     @type bool $encrypted
     *     @type string $etag
     *     @type string $ownerName
     *     @type string $storageId
     *     @type int|string $mountId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Fs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     * @return \OCA\Cloud_Py_API\Proto\fsId|null
     */
    public function getFileId()
    {
        return $this->fileId;
    }

    public function hasFileId()
    {
        return isset($this->fileId);
    }

    public function clearFileId()
    {
        unset($this->fileId);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.fsId fileId = 1;</code>
     * @param \OCA\Cloud_Py_API\Proto\fsId $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkMessage($var, \OCA\Cloud_Py_API\Proto\fsId::class);
        $this->fileId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 2;</code>
     * @return bool
     */
    public function getIsDir()
    {
        return $this->is_dir;
    }

    /**
     * Generated from protobuf field <code>bool is_dir = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDir($var)
    {
        GPBUtil::checkBool($var);
        $this->is_dir = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_local = 3;</code>
     * @return bool
     */
    public function getIsLocal()
    {
        return $this->is_local;
    }

    /**
     * Generated from protobuf field <code>bool is_local = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLocal($var)
    {
        GPBUtil::checkBool($var);
        $this->is_local = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mimetype = 4;</code>
     * @return string
     */
    public function getMimetype()
    {
        return $this->mimetype;
    }

    /**
     * Generated from protobuf field <code>string mimetype = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMimetype($var)
    {
        GPBUtil::checkString($var, True);
        $this->mimetype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string internal_path = 6;</code>
     * @return string
     */
    public function getInternalPath()
    {
        return $this->internal_path;
    }

    /**
     * Generated from protobuf field <code>string internal_path = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setInternalPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->internal_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string abs_path = 7;</code>
     * @return string
     */
    public function getAbsPath()
    {
        return $this->abs_path;
    }

    /**
     * Generated from protobuf field <code>string abs_path = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAbsPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->abs_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 size = 8;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int64 size = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 permissions = 9;</code>
     * @return int|string
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>int64 permissions = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPermissions($var)
    {
        GPBUtil::checkInt64($var);
        $this->permissions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mtime = 10;</code>
     * @return int|string
     */
    public function getMtime()
    {
        return $this->mtime;
    }

    /**
     * Generated from protobuf field <code>int64 mtime = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMtime($var)
    {
        GPBUtil::checkInt64($var);
        $this->mtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string checksum = 11;</code>
     * @return string
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Generated from protobuf field <code>string checksum = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkString($var, True);
        $this->checksum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool encrypted = 12;</code>
     * @return bool
     */
    public function getEncrypted()
    {
        return $this->encrypted;
    }

    /**
     * Generated from protobuf field <code>bool encrypted = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setEncrypted($var)
    {
        GPBUtil::checkBool($var);
        $this->encrypted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string etag = 13;</code>
     * @return string
     */
    public function getEtag()
    {
        return $this->etag;
    }

    /**
     * Generated from protobuf field <code>string etag = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setEtag($var)
    {
        GPBUtil::checkString($var, True);
        $this->etag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ownerName = 14;</code>
     * @return string
     */
    public function getOwnerName()
    {
        return $this->ownerName;
    }

    /**
     * Generated from protobuf field <code>string ownerName = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ownerName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storageId = 15;</code>
     * @return string
     */
    public function getStorageId()
    {
        return $this->storageId;
    }

    /**
     * Generated from protobuf field <code>string storageId = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->storageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 mountId = 16;</code>
     * @return int|string
     */
    public function getMountId()
    {
        return $this->mountId;
    }

    /**
     * Generated from protobuf field <code>int64 mountId = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->mountId = $var;

        return $this;
    }

}

