<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use UnexpectedValueException;

/**
 * docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level 
 *
 * Protobuf type <code>OCA.Cloud_Py_API.Proto.logLvl</code>
 */
class logLvl
{
    /**
     * Generated from protobuf enum <code>DEBUG = 0;</code>
     */
    const DEBUG = 0;
    /**
     * Generated from protobuf enum <code>INFO = 1;</code>
     */
    const INFO = 1;
    /**
     * Generated from protobuf enum <code>WARN = 2;</code>
     */
    const WARN = 2;
    /**
     * Generated from protobuf enum <code>ERROR = 3;</code>
     */
    const ERROR = 3;
    /**
     * Generated from protobuf enum <code>FATAL = 4;</code>
     */
    const FATAL = 4;

    private static $valueToName = [
        self::DEBUG => 'DEBUG',
        self::INFO => 'INFO',
        self::WARN => 'WARN',
        self::ERROR => 'ERROR',
        self::FATAL => 'FATAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

