<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>OCA.Cloud_Py_API.Proto.pType</code>
 */
class pType
{
    /**
     * Generated from protobuf enum <code>DEFAULT = 0;</code>
     */
    const PBDEFAULT = 0;
    /**
     * Generated from protobuf enum <code>NAMED = 1;</code>
     */
    const NAMED = 1;
    /**
     * Generated from protobuf enum <code>POSITIONAL = 2;</code>
     */
    const POSITIONAL = 2;

    private static $valueToName = [
        self::PBDEFAULT => 'PBDEFAULT',
        self::NAMED => 'NAMED',
        self::POSITIONAL => 'POSITIONAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

