<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

if (false) {
    /**
     * This class is deprecated. Use OCA\Cloud_Py_API\Proto\ServerCommand\cmd_id instead.
     * @deprecated
     */
    class ServerCommand_cmd_id {}
}
class_exists(ServerCommand\cmd_id::class);
@trigger_error('OCA\Cloud_Py_API\Proto\ServerCommand_cmd_id is deprecated and will be removed in the next major release. Use OCA\Cloud_Py_API\Proto\ServerCommand\cmd_id instead', E_USER_DEPRECATED);

