<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * No reply.
 *
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.TaskLogRequest</code>
 */
class TaskLogRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     */
    protected $log_lvl = 0;
    /**
     * What module logs belongs to.
     *
     * Generated from protobuf field <code>string module = 2;</code>
     */
    protected $module = '';
    /**
     * One or more strings to put to log.
     *
     * Generated from protobuf field <code>repeated string content = 3;</code>
     */
    private $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $log_lvl
     *     @type string $module
     *           What module logs belongs to.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $content
     *           One or more strings to put to log.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @return int
     */
    public function getLogLvl()
    {
        return $this->log_lvl;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogLvl($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\logLvl::class);
        $this->log_lvl = $var;

        return $this;
    }

    /**
     * What module logs belongs to.
     *
     * Generated from protobuf field <code>string module = 2;</code>
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * What module logs belongs to.
     *
     * Generated from protobuf field <code>string module = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->module = $var;

        return $this;
    }

    /**
     * One or more strings to put to log.
     *
     * Generated from protobuf field <code>repeated string content = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * One or more strings to put to log.
     *
     * Generated from protobuf field <code>repeated string content = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContent($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->content = $arr;

        return $this;
    }

}

