<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.TaskSetStatusRequest</code>
 */
class TaskSetStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Status code of a task.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.taskStatus st_code = 1;</code>
     */
    protected $st_code = 0;
    /**
     * Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     */
    protected $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $st_code
     *           Status code of a task.
     *     @type string $error
     *           Optional error, if any. Valid only when Status is non success/in_progress.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Status code of a task.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.taskStatus st_code = 1;</code>
     * @return int
     */
    public function getStCode()
    {
        return $this->st_code;
    }

    /**
     * Status code of a task.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.taskStatus st_code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStCode($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\taskStatus::class);
        $this->st_code = $var;

        return $this;
    }

    /**
     * Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

