<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>OCA.Cloud_Py_API.Proto.taskStatus</code>
 */
class taskStatus
{
    /**
     * Generated from protobuf enum <code>ST_SUCCESS = 0;</code>
     */
    const ST_SUCCESS = 0;
    /**
     * initialization is in progress
     *
     * Generated from protobuf enum <code>ST_INITIALIZING = 1;</code>
     */
    const ST_INITIALIZING = 1;
    /**
     * install is in progress
     *
     * Generated from protobuf enum <code>ST_INSTALLING = 2;</code>
     */
    const ST_INSTALLING = 2;
    /**
     * install return error
     *
     * Generated from protobuf enum <code>ST_INSTALL_ERROR = 3;</code>
     */
    const ST_INSTALL_ERROR = 3;
    /**
     * error during initialization target app
     *
     * Generated from protobuf enum <code>ST_INIT_ERROR = 4;</code>
     */
    const ST_INIT_ERROR = 4;
    /**
     * target app is running
     *
     * Generated from protobuf enum <code>ST_IN_PROGRESS = 5;</code>
     */
    const ST_IN_PROGRESS = 5;
    /**
     * Unexpected exception occurred
     *
     * Generated from protobuf enum <code>ST_EXCEPTION = 6;</code>
     */
    const ST_EXCEPTION = 6;
    /**
     * Default task state at start
     *
     * Generated from protobuf enum <code>ST_UNKNOWN = 7;</code>
     */
    const ST_UNKNOWN = 7;

    private static $valueToName = [
        self::ST_SUCCESS => 'ST_SUCCESS',
        self::ST_INITIALIZING => 'ST_INITIALIZING',
        self::ST_INSTALLING => 'ST_INSTALLING',
        self::ST_INSTALL_ERROR => 'ST_INSTALL_ERROR',
        self::ST_INIT_ERROR => 'ST_INIT_ERROR',
        self::ST_IN_PROGRESS => 'ST_IN_PROGRESS',
        self::ST_EXCEPTION => 'ST_EXCEPTION',
        self::ST_UNKNOWN => 'ST_UNKNOWN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

