<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace OCA\Cloud_Py_API\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *struct for `where` part.
 *
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.whereExpr</code>
 */
class whereExpr extends \Google\Protobuf\Internal\Message
{
    /**
     *where, andWhere, orWhere
     *
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     */
    protected $expression = '';
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.exprType expressionType = 3;</code>
     */
    protected $expressionType = 0;
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pType paramType = 4;</code>
     */
    protected $paramType = 0;
    /**
     * Generated from protobuf field <code>string paramColumn = 5;</code>
     */
    protected $paramColumn = '';
    /**
     * Generated from protobuf field <code>string paramValue = 6;</code>
     */
    protected $paramValue = '';
    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pValueType paramValueType = 7;</code>
     */
    protected $paramValueType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *          where, andWhere, orWhere
     *     @type string $expression
     *     @type int $expressionType
     *     @type int $paramType
     *     @type string $paramColumn
     *     @type string $paramValue
     *     @type int $paramValueType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     *where, andWhere, orWhere
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *where, andWhere, orWhere
     *
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     * @return string
     */
    public function getExpression()
    {
        return $this->expression;
    }

    /**
     * Generated from protobuf field <code>string expression = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpression($var)
    {
        GPBUtil::checkString($var, True);
        $this->expression = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.exprType expressionType = 3;</code>
     * @return int
     */
    public function getExpressionType()
    {
        return $this->expressionType;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.exprType expressionType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExpressionType($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\exprType::class);
        $this->expressionType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pType paramType = 4;</code>
     * @return int
     */
    public function getParamType()
    {
        return $this->paramType;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pType paramType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setParamType($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\pType::class);
        $this->paramType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paramColumn = 5;</code>
     * @return string
     */
    public function getParamColumn()
    {
        return $this->paramColumn;
    }

    /**
     * Generated from protobuf field <code>string paramColumn = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setParamColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->paramColumn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paramValue = 6;</code>
     * @return string
     */
    public function getParamValue()
    {
        return $this->paramValue;
    }

    /**
     * Generated from protobuf field <code>string paramValue = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setParamValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->paramValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pValueType paramValueType = 7;</code>
     * @return int
     */
    public function getParamValueType()
    {
        return $this->paramValueType;
    }

    /**
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.pValueType paramValueType = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setParamValueType($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\pValueType::class);
        $this->paramValueType = $var;

        return $this;
    }

}

