<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto\CheckDataRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.CheckDataRequest.installed_pckg</code>
 */
class installed_pckg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Format JSON: "8.4.0"
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * Path where it is installed.
     *
     * Generated from protobuf field <code>string location = 3;</code>
     */
    protected $location = '';
    /**
     * Description, what this package do.
     *
     * Generated from protobuf field <code>string summary = 4;</code>
     */
    protected $summary = '';
    /**
     * Depends on. In JSON format, array of string.
     *
     * Generated from protobuf field <code>string requires = 5;</code>
     */
    protected $requires = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $version
     *           Format JSON: "8.4.0"
     *     @type string $location
     *           Path where it is installed.
     *     @type string $summary
     *           Description, what this package do.
     *     @type string $requires
     *           Depends on. In JSON format, array of string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Format JSON: "8.4.0"
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Format JSON: "8.4.0"
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Path where it is installed.
     *
     * Generated from protobuf field <code>string location = 3;</code>
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Path where it is installed.
     *
     * Generated from protobuf field <code>string location = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;

        return $this;
    }

    /**
     * Description, what this package do.
     *
     * Generated from protobuf field <code>string summary = 4;</code>
     * @return string
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Description, what this package do.
     *
     * Generated from protobuf field <code>string summary = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkString($var, True);
        $this->summary = $var;

        return $this;
    }

    /**
     * Depends on. In JSON format, array of string.
     *
     * Generated from protobuf field <code>string requires = 5;</code>
     * @return string
     */
    public function getRequires()
    {
        return $this->requires;
    }

    /**
     * Depends on. In JSON format, array of string.
     *
     * Generated from protobuf field <code>string requires = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRequires($var)
    {
        GPBUtil::checkString($var, True);
        $this->requires = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(installed_pckg::class, \OCA\Cloud_Py_API\Proto\CheckDataRequest_installed_pckg::class);

