<?php
namespace OCA\Cloud_Py_API\TProto;

/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface TestServiceIf
{
    /**
     * @param int $logLvl
     * @return int
     */
    public function ping($logLvl);
    /**
     * @param int $resultCode
     */
    public function exit($resultCode);
}
