# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core__pb2
from . import fs_pb2 as fs__pb2
from . import db_pb2 as db__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='OCA.Cloud_Py_API.Proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x16OCA.Cloud_Py_API.Proto\x1a\ncore.proto\x1a\x08\x66s.proto\x1a\x08\x64\x62.proto2\xa1\x0b\n\x0e\x43loudPyApiCore\x12R\n\x08TaskInit\x12\x1d.OCA.Cloud_Py_API.Proto.Empty\x1a%.OCA.Cloud_Py_API.Proto.TaskInitReply\"\x00\x12[\n\nTaskStatus\x12,.OCA.Cloud_Py_API.Proto.TaskSetStatusRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12U\n\x08\x41ppCheck\x12(.OCA.Cloud_Py_API.Proto.CheckDataRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12T\n\x08TaskExit\x12\'.OCA.Cloud_Py_API.Proto.TaskExitRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12R\n\x07TaskLog\x12&.OCA.Cloud_Py_API.Proto.TaskLogRequest\x1a\x1d.OCA.Cloud_Py_API.Proto.Empty\"\x00\x12S\n\x07OccCall\x12\".OCA.Cloud_Py_API.Proto.OccRequest\x1a .OCA.Cloud_Py_API.Proto.OccReply\"\x00\x30\x01\x12\\\n\tFsGetInfo\x12(.OCA.Cloud_Py_API.Proto.FsGetInfoRequest\x1a#.OCA.Cloud_Py_API.Proto.FsListReply\"\x00\x12V\n\x06\x46sList\x12%.OCA.Cloud_Py_API.Proto.FsListRequest\x1a#.OCA.Cloud_Py_API.Proto.FsListReply\"\x00\x12X\n\x06\x46sRead\x12%.OCA.Cloud_Py_API.Proto.FsReadRequest\x1a#.OCA.Cloud_Py_API.Proto.FsReadReply\"\x00\x30\x01\x12\\\n\x08\x46sCreate\x12\'.OCA.Cloud_Py_API.Proto.FsCreateRequest\x1a%.OCA.Cloud_Py_API.Proto.FsCreateReply\"\x00\x12V\n\x07\x46sWrite\x12&.OCA.Cloud_Py_API.Proto.FsWriteRequest\x1a\x1f.OCA.Cloud_Py_API.Proto.FsReply\"\x00(\x01\x12V\n\x08\x46sDelete\x12\'.OCA.Cloud_Py_API.Proto.FsDeleteRequest\x1a\x1f.OCA.Cloud_Py_API.Proto.FsReply\"\x00\x12V\n\x06\x46sMove\x12%.OCA.Cloud_Py_API.Proto.FsMoveRequest\x1a#.OCA.Cloud_Py_API.Proto.FsMoveReply\"\x00\x12\\\n\x08\x44\x62Select\x12\'.OCA.Cloud_Py_API.Proto.DbSelectRequest\x1a%.OCA.Cloud_Py_API.Proto.DbSelectReply\"\x00\x12\\\n\x08\x44\x62\x43ursor\x12\'.OCA.Cloud_Py_API.Proto.DbCursorRequest\x1a%.OCA.Cloud_Py_API.Proto.DbCursorReply\"\x00\x12V\n\x06\x44\x62\x45xec\x12%.OCA.Cloud_Py_API.Proto.DbExecRequest\x1a#.OCA.Cloud_Py_API.Proto.DbExecReply\"\x00\x62\x06proto3'
  ,
  dependencies=[core__pb2.DESCRIPTOR,fs__pb2.DESCRIPTOR,db__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CLOUDPYAPICORE = _descriptor.ServiceDescriptor(
  name='CloudPyApiCore',
  full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=1515,
  methods=[
  _descriptor.MethodDescriptor(
    name='TaskInit',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.TaskInit',
    index=0,
    containing_service=None,
    input_type=core__pb2._EMPTY,
    output_type=core__pb2._TASKINITREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TaskStatus',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.TaskStatus',
    index=1,
    containing_service=None,
    input_type=core__pb2._TASKSETSTATUSREQUEST,
    output_type=core__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AppCheck',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.AppCheck',
    index=2,
    containing_service=None,
    input_type=core__pb2._CHECKDATAREQUEST,
    output_type=core__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TaskExit',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.TaskExit',
    index=3,
    containing_service=None,
    input_type=core__pb2._TASKEXITREQUEST,
    output_type=core__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TaskLog',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.TaskLog',
    index=4,
    containing_service=None,
    input_type=core__pb2._TASKLOGREQUEST,
    output_type=core__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OccCall',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.OccCall',
    index=5,
    containing_service=None,
    input_type=core__pb2._OCCREQUEST,
    output_type=core__pb2._OCCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsGetInfo',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsGetInfo',
    index=6,
    containing_service=None,
    input_type=fs__pb2._FSGETINFOREQUEST,
    output_type=fs__pb2._FSLISTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsList',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsList',
    index=7,
    containing_service=None,
    input_type=fs__pb2._FSLISTREQUEST,
    output_type=fs__pb2._FSLISTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsRead',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsRead',
    index=8,
    containing_service=None,
    input_type=fs__pb2._FSREADREQUEST,
    output_type=fs__pb2._FSREADREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsCreate',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsCreate',
    index=9,
    containing_service=None,
    input_type=fs__pb2._FSCREATEREQUEST,
    output_type=fs__pb2._FSCREATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsWrite',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsWrite',
    index=10,
    containing_service=None,
    input_type=fs__pb2._FSWRITEREQUEST,
    output_type=fs__pb2._FSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsDelete',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsDelete',
    index=11,
    containing_service=None,
    input_type=fs__pb2._FSDELETEREQUEST,
    output_type=fs__pb2._FSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FsMove',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.FsMove',
    index=12,
    containing_service=None,
    input_type=fs__pb2._FSMOVEREQUEST,
    output_type=fs__pb2._FSMOVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DbSelect',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.DbSelect',
    index=13,
    containing_service=None,
    input_type=db__pb2._DBSELECTREQUEST,
    output_type=db__pb2._DBSELECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DbCursor',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.DbCursor',
    index=14,
    containing_service=None,
    input_type=db__pb2._DBCURSORREQUEST,
    output_type=db__pb2._DBCURSORREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DbExec',
    full_name='OCA.Cloud_Py_API.Proto.CloudPyApiCore.DbExec',
    index=15,
    containing_service=None,
    input_type=db__pb2._DBEXECREQUEST,
    output_type=db__pb2._DBEXECREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUDPYAPICORE)

DESCRIPTOR.services_by_name['CloudPyApiCore'] = _CLOUDPYAPICORE

# @@protoc_insertion_point(module_scope)
