<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto\TaskInitReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.TaskInitReply.cfgOptions</code>
 */
class cfgOptions extends \Google\Protobuf\Internal\Message
{
    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     */
    protected $log_lvl = 0;
    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     */
    protected $dataFolder = '';
    /**
     *Path to cloud_py_api app data folder.
     *
     * Generated from protobuf field <code>string frameworkAppData = 3;</code>
     */
    protected $frameworkAppData = '';
    /**
     *Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 4;</code>
     */
    protected $userId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $log_lvl
     *          0-4 , level logs from NC documentation.
     *     @type string $dataFolder
     *          Path to NC data folder.
     *     @type string $frameworkAppData
     *          Path to cloud_py_api app data folder.
     *     @type string $userId
     *          Current NC user UID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @return int
     */
    public function getLogLvl()
    {
        return $this->log_lvl;
    }

    /**
     *0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogLvl($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\logLvl::class);
        $this->log_lvl = $var;

        return $this;
    }

    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @return string
     */
    public function getDataFolder()
    {
        return $this->dataFolder;
    }

    /**
     *Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDataFolder($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataFolder = $var;

        return $this;
    }

    /**
     *Path to cloud_py_api app data folder.
     *
     * Generated from protobuf field <code>string frameworkAppData = 3;</code>
     * @return string
     */
    public function getFrameworkAppData()
    {
        return $this->frameworkAppData;
    }

    /**
     *Path to cloud_py_api app data folder.
     *
     * Generated from protobuf field <code>string frameworkAppData = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFrameworkAppData($var)
    {
        GPBUtil::checkString($var, True);
        $this->frameworkAppData = $var;

        return $this;
    }

    /**
     *Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 4;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     *Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(cfgOptions::class, \OCA\Cloud_Py_API\Proto\TaskInitReply_cfgOptions::class);

