<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace OCA\Cloud_Py_API\Proto\TaskInitReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OCA.Cloud_Py_API.Proto.TaskInitReply.cfgOptions</code>
 */
class cfgOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * 0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     */
    protected $log_lvl = 0;
    /**
     * Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     */
    protected $dataFolder = '';
    /**
     * Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     */
    protected $userId = '';
    /**
     * Use extra direct FS module for python, when possible.
     *
     * Generated from protobuf field <code>bool useFileDirect = 4;</code>
     */
    protected $useFileDirect = false;
    /**
     * Use extra direct DB module for python, if possible.
     *
     * Generated from protobuf field <code>bool useDBDirect = 5;</code>
     */
    protected $useDBDirect = false;
    /**
     * Maximum chunk size of RPC stream data.
     *
     * Generated from protobuf field <code>int32 maxChunkSize = 6;</code>
     */
    protected $maxChunkSize = 0;
    /**
     * Maximum chunk size for FS Create operations
     *
     * Generated from protobuf field <code>int32 maxCreateFileContent = 7;</code>
     */
    protected $maxCreateFileContent = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $log_lvl
     *           0-4 , level logs from NC documentation.
     *     @type string $dataFolder
     *           Path to NC data folder.
     *     @type string $userId
     *           Current NC user UID
     *     @type bool $useFileDirect
     *           Use extra direct FS module for python, when possible.
     *     @type bool $useDBDirect
     *           Use extra direct DB module for python, if possible.
     *     @type int $maxChunkSize
     *           Maximum chunk size of RPC stream data.
     *     @type int $maxCreateFileContent
     *           Maximum chunk size for FS Create operations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * 0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @return int
     */
    public function getLogLvl()
    {
        return $this->log_lvl;
    }

    /**
     * 0-4 , level logs from NC documentation.
     *
     * Generated from protobuf field <code>.OCA.Cloud_Py_API.Proto.logLvl log_lvl = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLogLvl($var)
    {
        GPBUtil::checkEnum($var, \OCA\Cloud_Py_API\Proto\logLvl::class);
        $this->log_lvl = $var;

        return $this;
    }

    /**
     * Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @return string
     */
    public function getDataFolder()
    {
        return $this->dataFolder;
    }

    /**
     * Path to NC data folder.
     *
     * Generated from protobuf field <code>string dataFolder = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDataFolder($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataFolder = $var;

        return $this;
    }

    /**
     * Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Current NC user UID
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * Use extra direct FS module for python, when possible.
     *
     * Generated from protobuf field <code>bool useFileDirect = 4;</code>
     * @return bool
     */
    public function getUseFileDirect()
    {
        return $this->useFileDirect;
    }

    /**
     * Use extra direct FS module for python, when possible.
     *
     * Generated from protobuf field <code>bool useFileDirect = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseFileDirect($var)
    {
        GPBUtil::checkBool($var);
        $this->useFileDirect = $var;

        return $this;
    }

    /**
     * Use extra direct DB module for python, if possible.
     *
     * Generated from protobuf field <code>bool useDBDirect = 5;</code>
     * @return bool
     */
    public function getUseDBDirect()
    {
        return $this->useDBDirect;
    }

    /**
     * Use extra direct DB module for python, if possible.
     *
     * Generated from protobuf field <code>bool useDBDirect = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseDBDirect($var)
    {
        GPBUtil::checkBool($var);
        $this->useDBDirect = $var;

        return $this;
    }

    /**
     * Maximum chunk size of RPC stream data.
     *
     * Generated from protobuf field <code>int32 maxChunkSize = 6;</code>
     * @return int
     */
    public function getMaxChunkSize()
    {
        return $this->maxChunkSize;
    }

    /**
     * Maximum chunk size of RPC stream data.
     *
     * Generated from protobuf field <code>int32 maxChunkSize = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxChunkSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxChunkSize = $var;

        return $this;
    }

    /**
     * Maximum chunk size for FS Create operations
     *
     * Generated from protobuf field <code>int32 maxCreateFileContent = 7;</code>
     * @return int
     */
    public function getMaxCreateFileContent()
    {
        return $this->maxCreateFileContent;
    }

    /**
     * Maximum chunk size for FS Create operations
     *
     * Generated from protobuf field <code>int32 maxCreateFileContent = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxCreateFileContent($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxCreateFileContent = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(cfgOptions::class, \OCA\Cloud_Py_API\Proto\TaskInitReply_cfgOptions::class);

