<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

namespace Cloud_Py_API\ServerCommand;

use UnexpectedValueException;

/**
 * Protobuf type <code>Cloud_Py_API.ServerCommand.cmd_id</code>
 */
class cmd_id
{
    /**
     * Generated from protobuf enum <code>TASK_NOTHING = 0;</code>
     */
    const TASK_NOTHING = 0;
    /**
     * Generated from protobuf enum <code>TASK_STOP = 1;</code>
     */
    const TASK_STOP = 1;

    private static $valueToName = [
        self::TASK_NOTHING => 'TASK_NOTHING',
        self::TASK_STOP => 'TASK_STOP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(cmd_id::class, \Cloud_Py_API\ServerCommand_cmd_id::class);

