<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use DbCursorRequest\cCmd instead.
     * @deprecated
     */
    class DbCursorRequest_cCmd {}
}
class_exists(DbCursorRequest\cCmd::class);
@trigger_error('DbCursorRequest_cCmd is deprecated and will be removed in the next major release. Use DbCursorRequest\cCmd instead', E_USER_DEPRECATED);

