<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use DbExecRequest\rType instead.
     * @deprecated
     */
    class DbExecRequest_rType {}
}
class_exists(DbExecRequest\rType::class);
@trigger_error('DbExecRequest_rType is deprecated and will be removed in the next major release. Use DbExecRequest\rType instead', E_USER_DEPRECATED);

