<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DbExec</code>
 */
class DbExec extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.DB_EXEC
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     * Generated from protobuf field <code>.dbExecType type = 2;</code>
     */
    protected $type = 0;
    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated string what = 3;</code>
     */
    private $what;
    /**
     *TODO: values
     *
     * Generated from protobuf field <code>repeated .whereExpr whereas = 6;</code>
     */
    private $whereas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.DB_EXEC
     *     @type int $type
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $what
     *          aliases or filed names.
     *     @type \whereExpr[]|\Google\Protobuf\Internal\RepeatedField $whereas
     *          TODO: values
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.DB_EXEC
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.DB_EXEC
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dbExecType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.dbExecType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \dbExecType::class);
        $this->type = $var;

        return $this;
    }

    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated string what = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhat()
    {
        return $this->what;
    }

    /**
     *aliases or filed names.
     *
     * Generated from protobuf field <code>repeated string what = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhat($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->what = $arr;

        return $this;
    }

    /**
     *TODO: values
     *
     * Generated from protobuf field <code>repeated .whereExpr whereas = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWhereas()
    {
        return $this->whereas;
    }

    /**
     *TODO: values
     *
     * Generated from protobuf field <code>repeated .whereExpr whereas = 6;</code>
     * @param \whereExpr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWhereas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \whereExpr::class);
        $this->whereas = $arr;

        return $this;
    }

}

