<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use DbSelect\joinType instead.
     * @deprecated
     */
    class DbSelect_joinType {}
}
class_exists(DbSelect\joinType::class);
@trigger_error('DbSelect_joinType is deprecated and will be removed in the next major release. Use DbSelect\joinType instead', E_USER_DEPRECATED);

