<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use DbSelectRequest\havingExpr instead.
     * @deprecated
     */
    class DbSelectRequest_havingExpr {}
}
class_exists(DbSelectRequest\havingExpr::class);
@trigger_error('DbSelectRequest_havingExpr is deprecated and will be removed in the next major release. Use DbSelectRequest\havingExpr instead', E_USER_DEPRECATED);

