<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FsListRequest</code>
 */
class FsListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fsId dirId = 1;</code>
     */
    protected $dirId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \fsId $dirId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fsId dirId = 1;</code>
     * @return \fsId|null
     */
    public function getDirId()
    {
        return $this->dirId;
    }

    public function hasDirId()
    {
        return isset($this->dirId);
    }

    public function clearDirId()
    {
        unset($this->dirId);
    }

    /**
     * Generated from protobuf field <code>.fsId dirId = 1;</code>
     * @param \fsId $var
     * @return $this
     */
    public function setDirId($var)
    {
        GPBUtil::checkMessage($var, \fsId::class);
        $this->dirId = $var;

        return $this;
    }

}

