<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FsRead</code>
 */
class FsRead extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.FS_READ
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     */
    protected $userID = '';
    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     */
    protected $fileID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.FS_READ
     *     @type string $userID
     *     @type string $fileID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.FS_READ
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.FS_READ
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     * @return string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkString($var, True);
        $this->userID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     * @return string
     */
    public function getFileID()
    {
        return $this->fileID;
    }

    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFileID($var)
    {
        GPBUtil::checkString($var, True);
        $this->fileID = $var;

        return $this;
    }

}

