<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FsReply</code>
 */
class FsReply extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.(FS_CREATE || FS_WRITE || FS_DELETE || FS_MOVE)
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     * Generated from protobuf field <code>.fsResultCode resCode = 2;</code>
     */
    protected $resCode = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.(FS_CREATE || FS_WRITE || FS_DELETE || FS_MOVE)
     *     @type int $resCode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.(FS_CREATE || FS_WRITE || FS_DELETE || FS_MOVE)
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.(FS_CREATE || FS_WRITE || FS_DELETE || FS_MOVE)
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fsResultCode resCode = 2;</code>
     * @return int
     */
    public function getResCode()
    {
        return $this->resCode;
    }

    /**
     * Generated from protobuf field <code>.fsResultCode resCode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResCode($var)
    {
        GPBUtil::checkEnum($var, \fsResultCode::class);
        $this->resCode = $var;

        return $this;
    }

}

