<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Reply for this is a FsReply message.
 *
 * Generated from protobuf message <code>FsWriteRequest</code>
 */
class FsWriteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fsId fileId = 1;</code>
     */
    protected $fileId = null;
    /**
     * Generated from protobuf field <code>bytes content = 2;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \fsId $fileId
     *     @type string $content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fsId fileId = 1;</code>
     * @return \fsId|null
     */
    public function getFileId()
    {
        return $this->fileId;
    }

    public function hasFileId()
    {
        return isset($this->fileId);
    }

    public function clearFileId()
    {
        unset($this->fileId);
    }

    /**
     * Generated from protobuf field <code>.fsId fileId = 1;</code>
     * @param \fsId $var
     * @return $this
     */
    public function setFileId($var)
    {
        GPBUtil::checkMessage($var, \fsId::class);
        $this->fileId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>bytes content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;

        return $this;
    }

}

