<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Read\Write request for file.
 *
 * Generated from protobuf message <code>GetFileContent</code>
 */
class GetFileContent extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.GET_FILE_CONTENT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     */
    protected $userID = '';
    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     */
    protected $fileID = '';
    /**
     *Present only in reply from server.
     *
     * Generated from protobuf field <code>.FsResultCode resCode = 4;</code>
     */
    protected $resCode = 0;
    /**
     *Present only in reply from server and if ResultCode is success.
     *
     * Generated from protobuf field <code>bytes fileContent = 5;</code>
     */
    protected $fileContent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.GET_FILE_CONTENT
     *     @type string $userID
     *     @type string $fileID
     *     @type int $resCode
     *          Present only in reply from server.
     *     @type string $fileContent
     *          Present only in reply from server and if ResultCode is success.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.GET_FILE_CONTENT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.GET_FILE_CONTENT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     * @return string
     */
    public function getUserID()
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>string userID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserID($var)
    {
        GPBUtil::checkString($var, True);
        $this->userID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     * @return string
     */
    public function getFileID()
    {
        return $this->fileID;
    }

    /**
     * Generated from protobuf field <code>string fileID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFileID($var)
    {
        GPBUtil::checkString($var, True);
        $this->fileID = $var;

        return $this;
    }

    /**
     *Present only in reply from server.
     *
     * Generated from protobuf field <code>.FsResultCode resCode = 4;</code>
     * @return int
     */
    public function getResCode()
    {
        return $this->resCode;
    }

    /**
     *Present only in reply from server.
     *
     * Generated from protobuf field <code>.FsResultCode resCode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setResCode($var)
    {
        GPBUtil::checkEnum($var, \FsResultCode::class);
        $this->resCode = $var;

        return $this;
    }

    /**
     *Present only in reply from server and if ResultCode is success.
     *
     * Generated from protobuf field <code>bytes fileContent = 5;</code>
     * @return string
     */
    public function getFileContent()
    {
        return $this->fileContent;
    }

    /**
     *Present only in reply from server and if ResultCode is success.
     *
     * Generated from protobuf field <code>bytes fileContent = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->fileContent = $var;

        return $this;
    }

}

