<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Reply from server for request with msgId = 1.
 *
 * Generated from protobuf message <code>InitTask</code>
 */
class InitTask extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.INIT_TASK
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     *Path to target app directory, to be executed.
     *
     * Generated from protobuf field <code>string appPath = 2;</code>
     */
    protected $appPath = '';
    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 6;</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>.InitTask.ConfigOptions config = 7;</code>
     */
    protected $config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.INIT_TASK
     *     @type string $appPath
     *          Path to target app directory, to be executed.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $args
     *          Optional arguments to pass to target python app's module.
     *     @type \InitTask\ConfigOptions $config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.INIT_TASK
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.INIT_TASK
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     *Path to target app directory, to be executed.
     *
     * Generated from protobuf field <code>string appPath = 2;</code>
     * @return string
     */
    public function getAppPath()
    {
        return $this->appPath;
    }

    /**
     *Path to target app directory, to be executed.
     *
     * Generated from protobuf field <code>string appPath = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->appPath = $var;

        return $this;
    }

    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.InitTask.ConfigOptions config = 7;</code>
     * @return \InitTask\ConfigOptions|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Generated from protobuf field <code>.InitTask.ConfigOptions config = 7;</code>
     * @param \InitTask\ConfigOptions $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \InitTask\ConfigOptions::class);
        $this->config = $var;

        return $this;
    }

}

