<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use Select\HavingExpr instead.
     * @deprecated
     */
    class Select_HavingExpr {}
}
class_exists(Select\HavingExpr::class);
@trigger_error('Select_HavingExpr is deprecated and will be removed in the next major release. Use Select\HavingExpr instead', E_USER_DEPRECATED);

