<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use Select\JoinType instead.
     * @deprecated
     */
    class Select_JoinType {}
}
class_exists(Select\JoinType::class);
@trigger_error('Select_JoinType is deprecated and will be removed in the next major release. Use Select\JoinType instead', E_USER_DEPRECATED);

