<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

if (false) {
    /**
     * This class is deprecated. Use TaskInitReply\cfgOptions instead.
     * @deprecated
     */
    class TaskInitReply_cfgOptions {}
}
class_exists(TaskInitReply\cfgOptions::class);
@trigger_error('TaskInitReply_cfgOptions is deprecated and will be removed in the next major release. Use TaskInitReply\cfgOptions instead', E_USER_DEPRECATED);

