<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Reply for TASK_GET_STATE. Client send it every ~5 sec.
 *
 * Generated from protobuf message <code>TaskGetStateReply</code>
 */
class TaskGetStateReply extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.TASK_GET_STATE
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool bStop = 2;</code>
     */
    protected $bStop = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.TASK_GET_STATE
     *     @type bool $bStop
     *          If true client must gracefully stop it's work.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.TASK_GET_STATE
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.TASK_GET_STATE
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool bStop = 2;</code>
     * @return bool
     */
    public function getBStop()
    {
        return $this->bStop;
    }

    /**
     *If true client must gracefully stop it's work.
     *
     * Generated from protobuf field <code>bool bStop = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBStop($var)
    {
        GPBUtil::checkBool($var);
        $this->bStop = $var;

        return $this;
    }

}

