<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *Write request. No reply. Server must close pipe/socket after this message.
 *
 * Generated from protobuf message <code>TaskExit</code>
 */
class TaskExit extends \Google\Protobuf\Internal\Message
{
    /**
     *msgClass.TASK_EXIT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     *Optional text, for exit action. Ignored in most cases.
     *
     * Generated from protobuf field <code>string msgText = 8;</code>
     */
    protected $msgText = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          msgClass.TASK_EXIT
     *     @type string $msgText
     *          Optional text, for exit action. Ignored in most cases.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *msgClass.TASK_EXIT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *msgClass.TASK_EXIT
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     *Optional text, for exit action. Ignored in most cases.
     *
     * Generated from protobuf field <code>string msgText = 8;</code>
     * @return string
     */
    public function getMsgText()
    {
        return $this->msgText;
    }

    /**
     *Optional text, for exit action. Ignored in most cases.
     *
     * Generated from protobuf field <code>string msgText = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgText($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgText = $var;

        return $this;
    }

}

