<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *No reply.
 *
 * Generated from protobuf message <code>TaskStatus</code>
 */
class TaskStatus extends \Google\Protobuf\Internal\Message
{
    /**
     *TaskStatus.TASK_STATUS
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     */
    protected $classId = 0;
    /**
     *Status code of a task.
     *
     * Generated from protobuf field <code>.taskStatus st_code = 2;</code>
     */
    protected $st_code = 0;
    /**
     *Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 3;</code>
     */
    protected $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $classId
     *          TaskStatus.TASK_STATUS
     *     @type int $st_code
     *          Status code of a task.
     *     @type string $error
     *          Optional error, if any. Valid only when Status is non success/in_progress.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *TaskStatus.TASK_STATUS
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @return int
     */
    public function getClassId()
    {
        return $this->classId;
    }

    /**
     *TaskStatus.TASK_STATUS
     *
     * Generated from protobuf field <code>.msgClass classId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setClassId($var)
    {
        GPBUtil::checkEnum($var, \msgClass::class);
        $this->classId = $var;

        return $this;
    }

    /**
     *Status code of a task.
     *
     * Generated from protobuf field <code>.taskStatus st_code = 2;</code>
     * @return int
     */
    public function getStCode()
    {
        return $this->st_code;
    }

    /**
     *Status code of a task.
     *
     * Generated from protobuf field <code>.taskStatus st_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStCode($var)
    {
        GPBUtil::checkEnum($var, \taskStatus::class);
        $this->st_code = $var;

        return $this;
    }

    /**
     *Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 3;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     *Optional error, if any. Valid only when Status is non success/in_progress.
     *
     * Generated from protobuf field <code>string error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

