<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TaskInitReply</code>
 */
class TaskInitReply extends \Google\Protobuf\Internal\Message
{
    /**
     *Path to file, to be executed.
     *
     * Generated from protobuf field <code>string filePath = 1;</code>
     */
    protected $filePath = '';
    /**
     *Which function to execute(optional).
     *
     * Generated from protobuf field <code>string funcName = 2;</code>
     */
    protected $funcName = '';
    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 3;</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>.TaskInitReply.cfgOptions config = 4;</code>
     */
    protected $config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $filePath
     *          Path to file, to be executed.
     *     @type string $funcName
     *          Which function to execute(optional).
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $args
     *          Optional arguments to pass to target python app's module.
     *     @type \TaskInitReply\cfgOptions $config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Core::initOnce();
        parent::__construct($data);
    }

    /**
     *Path to file, to be executed.
     *
     * Generated from protobuf field <code>string filePath = 1;</code>
     * @return string
     */
    public function getFilePath()
    {
        return $this->filePath;
    }

    /**
     *Path to file, to be executed.
     *
     * Generated from protobuf field <code>string filePath = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFilePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->filePath = $var;

        return $this;
    }

    /**
     *Which function to execute(optional).
     *
     * Generated from protobuf field <code>string funcName = 2;</code>
     * @return string
     */
    public function getFuncName()
    {
        return $this->funcName;
    }

    /**
     *Which function to execute(optional).
     *
     * Generated from protobuf field <code>string funcName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFuncName($var)
    {
        GPBUtil::checkString($var, True);
        $this->funcName = $var;

        return $this;
    }

    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     *Optional arguments to pass to target python app's module.
     *
     * Generated from protobuf field <code>repeated string args = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TaskInitReply.cfgOptions config = 4;</code>
     * @return \TaskInitReply\cfgOptions|null
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function hasConfig()
    {
        return isset($this->config);
    }

    public function clearConfig()
    {
        unset($this->config);
    }

    /**
     * Generated from protobuf field <code>.TaskInitReply.cfgOptions config = 4;</code>
     * @param \TaskInitReply\cfgOptions $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \TaskInitReply\cfgOptions::class);
        $this->config = $var;

        return $this;
    }

}

